// Code generated by MockGen. DO NOT EDIT.
// Source: deleter.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataDeleteServ is a mock of DataDeleteServ interface.
type MockDataDeleteServ struct {
	ctrl     *gomock.Controller
	recorder *MockDataDeleteServMockRecorder
}

// MockDataDeleteServMockRecorder is the mock recorder for MockDataDeleteServ.
type MockDataDeleteServMockRecorder struct {
	mock *MockDataDeleteServ
}

// NewMockDataDeleteServ creates a new mock instance.
func NewMockDataDeleteServ(ctrl *gomock.Controller) *MockDataDeleteServ {
	mock := &MockDataDeleteServ{ctrl: ctrl}
	mock.recorder = &MockDataDeleteServMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataDeleteServ) EXPECT() *MockDataDeleteServMockRecorder {
	return m.recorder
}

// DeleteData mocks base method.
func (m *MockDataDeleteServ) DeleteData(ctx context.Context, dataID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteData", ctx, dataID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteData indicates an expected call of DeleteData.
func (mr *MockDataDeleteServMockRecorder) DeleteData(ctx, dataID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteData", reflect.TypeOf((*MockDataDeleteServ)(nil).DeleteData), ctx, dataID, userID)
}
