// Code generated by MockGen. DO NOT EDIT.
// Source: getter.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/Te8va/GophKeeper/internal/app/domain"
)

// MockDataGetterServ is a mock of DataGetterServ interface.
type MockDataGetterServ struct {
	ctrl     *gomock.Controller
	recorder *MockDataGetterServMockRecorder
}

// MockDataGetterServMockRecorder is the mock recorder for MockDataGetterServ.
type MockDataGetterServMockRecorder struct {
	mock *MockDataGetterServ
}

// NewMockDataGetterServ creates a new mock instance.
func NewMockDataGetterServ(ctrl *gomock.Controller) *MockDataGetterServ {
	mock := &MockDataGetterServ{ctrl: ctrl}
	mock.recorder = &MockDataGetterServMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataGetterServ) EXPECT() *MockDataGetterServMockRecorder {
	return m.recorder
}

// GetAllUserData mocks base method.
func (m *MockDataGetterServ) GetAllUserData(ctx context.Context, userID string) ([]*domain.DataRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserData", ctx, userID)
	ret0, _ := ret[0].([]*domain.DataRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserData indicates an expected call of GetAllUserData.
func (mr *MockDataGetterServMockRecorder) GetAllUserData(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserData", reflect.TypeOf((*MockDataGetterServ)(nil).GetAllUserData), ctx, userID)
}

// GetDataByID mocks base method.
func (m *MockDataGetterServ) GetDataByID(ctx context.Context, dataID, userID string) (*domain.DataRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByID", ctx, dataID, userID)
	ret0, _ := ret[0].(*domain.DataRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByID indicates an expected call of GetDataByID.
func (mr *MockDataGetterServMockRecorder) GetDataByID(ctx, dataID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByID", reflect.TypeOf((*MockDataGetterServ)(nil).GetDataByID), ctx, dataID, userID)
}
