// Code generated by MockGen. DO NOT EDIT.
// Source: authorization.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/Te8va/GophKeeper/internal/app/domain"
)

// MockAuthorizationServ is a mock of AuthorizationServ interface.
type MockAuthorizationServ struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationServMockRecorder
}

// MockAuthorizationServMockRecorder is the mock recorder for MockAuthorizationServ.
type MockAuthorizationServMockRecorder struct {
	mock *MockAuthorizationServ
}

// NewMockAuthorizationServ creates a new mock instance.
func NewMockAuthorizationServ(ctrl *gomock.Controller) *MockAuthorizationServ {
	mock := &MockAuthorizationServ{ctrl: ctrl}
	mock.recorder = &MockAuthorizationServMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationServ) EXPECT() *MockAuthorizationServMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockAuthorizationServ) CreateUser(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthorizationServMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthorizationServ)(nil).CreateUser), ctx, user)
}

// GetUserByLogin mocks base method.
func (m *MockAuthorizationServ) GetUserByLogin(ctx context.Context, login string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockAuthorizationServMockRecorder) GetUserByLogin(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockAuthorizationServ)(nil).GetUserByLogin), ctx, login)
}
