// Code generated by MockGen. DO NOT EDIT.
// Source: saver.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/Te8va/GophKeeper/internal/app/domain"
)

// MockDataSaverServ is a mock of DataSaverServ interface.
type MockDataSaverServ struct {
	ctrl     *gomock.Controller
	recorder *MockDataSaverServMockRecorder
}

// MockDataSaverServMockRecorder is the mock recorder for MockDataSaverServ.
type MockDataSaverServMockRecorder struct {
	mock *MockDataSaverServ
}

// NewMockDataSaverServ creates a new mock instance.
func NewMockDataSaverServ(ctrl *gomock.Controller) *MockDataSaverServ {
	mock := &MockDataSaverServ{ctrl: ctrl}
	mock.recorder = &MockDataSaverServMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSaverServ) EXPECT() *MockDataSaverServMockRecorder {
	return m.recorder
}

// CreateData mocks base method.
func (m *MockDataSaverServ) CreateData(ctx context.Context, userID string, req *domain.DataRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateData", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateData indicates an expected call of CreateData.
func (mr *MockDataSaverServMockRecorder) CreateData(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateData", reflect.TypeOf((*MockDataSaverServ)(nil).CreateData), ctx, userID, req)
}

// UpdateData mocks base method.
func (m *MockDataSaverServ) UpdateData(ctx context.Context, userID string, req *domain.DataRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateData", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateData indicates an expected call of UpdateData.
func (mr *MockDataSaverServMockRecorder) UpdateData(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateData", reflect.TypeOf((*MockDataSaverServ)(nil).UpdateData), ctx, userID, req)
}
