// Code generated by MockGen. DO NOT EDIT.
// Source: savehandler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/Te8va/GophKeeper/internal/app/domain"
)

// MockDataSaver is a mock of DataSaver interface.
type MockDataSaver struct {
	ctrl     *gomock.Controller
	recorder *MockDataSaverMockRecorder
}

// MockDataSaverMockRecorder is the mock recorder for MockDataSaver.
type MockDataSaverMockRecorder struct {
	mock *MockDataSaver
}

// NewMockDataSaver creates a new mock instance.
func NewMockDataSaver(ctrl *gomock.Controller) *MockDataSaver {
	mock := &MockDataSaver{ctrl: ctrl}
	mock.recorder = &MockDataSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSaver) EXPECT() *MockDataSaverMockRecorder {
	return m.recorder
}

// CreateData mocks base method.
func (m *MockDataSaver) CreateData(ctx context.Context, userID string, req *domain.DataRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateData", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateData indicates an expected call of CreateData.
func (mr *MockDataSaverMockRecorder) CreateData(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateData", reflect.TypeOf((*MockDataSaver)(nil).CreateData), ctx, userID, req)
}

// UpdateData mocks base method.
func (m *MockDataSaver) UpdateData(ctx context.Context, userID string, req *domain.DataRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateData", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateData indicates an expected call of UpdateData.
func (mr *MockDataSaverMockRecorder) UpdateData(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateData", reflect.TypeOf((*MockDataSaver)(nil).UpdateData), ctx, userID, req)
}
