// Code generated by MockGen. DO NOT EDIT.
// Source: deletehandler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataDelete is a mock of DataDelete interface.
type MockDataDelete struct {
	ctrl     *gomock.Controller
	recorder *MockDataDeleteMockRecorder
}

// MockDataDeleteMockRecorder is the mock recorder for MockDataDelete.
type MockDataDeleteMockRecorder struct {
	mock *MockDataDelete
}

// NewMockDataDelete creates a new mock instance.
func NewMockDataDelete(ctrl *gomock.Controller) *MockDataDelete {
	mock := &MockDataDelete{ctrl: ctrl}
	mock.recorder = &MockDataDeleteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataDelete) EXPECT() *MockDataDeleteMockRecorder {
	return m.recorder
}

// DeleteData mocks base method.
func (m *MockDataDelete) DeleteData(ctx context.Context, dataID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteData", ctx, dataID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteData indicates an expected call of DeleteData.
func (mr *MockDataDeleteMockRecorder) DeleteData(ctx, dataID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteData", reflect.TypeOf((*MockDataDelete)(nil).DeleteData), ctx, dataID, userID)
}
