// Code generated by MockGen. DO NOT EDIT.
// Source: gethandler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/Te8va/GophKeeper/internal/app/domain"
)

// MockDataGetter is a mock of DataGetter interface.
type MockDataGetter struct {
	ctrl     *gomock.Controller
	recorder *MockDataGetterMockRecorder
}

// MockDataGetterMockRecorder is the mock recorder for MockDataGetter.
type MockDataGetterMockRecorder struct {
	mock *MockDataGetter
}

// NewMockDataGetter creates a new mock instance.
func NewMockDataGetter(ctrl *gomock.Controller) *MockDataGetter {
	mock := &MockDataGetter{ctrl: ctrl}
	mock.recorder = &MockDataGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataGetter) EXPECT() *MockDataGetterMockRecorder {
	return m.recorder
}

// GetAllUserData mocks base method.
func (m *MockDataGetter) GetAllUserData(ctx context.Context, userID string) ([]*domain.DataRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserData", ctx, userID)
	ret0, _ := ret[0].([]*domain.DataRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserData indicates an expected call of GetAllUserData.
func (mr *MockDataGetterMockRecorder) GetAllUserData(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserData", reflect.TypeOf((*MockDataGetter)(nil).GetAllUserData), ctx, userID)
}

// GetDataByID mocks base method.
func (m *MockDataGetter) GetDataByID(ctx context.Context, dataID, userID string) (*domain.DataRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByID", ctx, dataID, userID)
	ret0, _ := ret[0].(*domain.DataRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByID indicates an expected call of GetDataByID.
func (mr *MockDataGetterMockRecorder) GetDataByID(ctx, dataID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByID", reflect.TypeOf((*MockDataGetter)(nil).GetDataByID), ctx, dataID, userID)
}
